package greedy;
import java.util.*;

// Problem Title => Huffman Coding

// node class is the basic structure of each node present in the Huffman - tree.
class HuffmanNode{
    int data;
    char c;
    HuffmanNode left, right;
}

// Comparator class helps to compare the node on the basis of one of its attribute.
// Here we will be compared on the basis of data values of the nodes.
class MyComparator implements Comparable<HuffmanNode>{
    public int compare(HuffmanNode x, HuffmanNode y){
        return x.data - y.data;
    }

    @Override
    public int compareTo(HuffmanNode o) {
        return 0;
    }
}


public class Problem_3 {

    static void printCode(HuffmanNode root, String s){

        // base case => if the left and right are null then it's a leaf node,
        // and we print the code s generated by traversing the tree.
        if(root.left == null && root.right == null && Character.isLetter(root.c)){
            // c is the character in the node
            System.out.println(root.c + ":" + s);

            return;
        }

        // if we go to left then add "0" to the code.
        // if we go to the right add"1" to the code.

        // recursive calls for left and
        // right sub-tree of the generated tree.
        printCode(root.left, s + "0");
        printCode(root.right, s + "1");
    }


    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        int n = sc.nextInt();
        char[] charArray = new char[n];
        for(int i = 0; i < n; i++){
            charArray[i] = sc.next().charAt(i);
        }

        // Taking char_freq arrays.array as input from user
        int[] char_freq = new int[n];
        for(int i = 0; i < n; i++){
            char_freq[i] = sc.nextInt();
        }

        // creating a priority queue q.
        // makes a min-priority queue(min-heap).
        PriorityQueue<HuffmanNode> q = new PriorityQueue<HuffmanNode>(n, (Comparator<? super HuffmanNode>) new MyComparator());

        for (int i = 0; i < n; i++) {

            // creating a Huffman node object and add it to the priority queue.
            HuffmanNode hn = new HuffmanNode();

            hn.c = charArray[i];
            hn.data = char_freq[i];

            hn.left = null;
            hn.right = null;

            // add functions adds
            // the huffman node to the queue.
            q.add(hn);
        }

        // create a root node
        HuffmanNode root = null;

        // Here we will extract the two minimum value from the heap each time until its size reduces to 1,
        // extract until all the nodes are extracted.
        while (q.size() > 1) {

            // first min extract.
            HuffmanNode x = q.peek();
            q.poll();

            // second min extract.
            HuffmanNode y = q.peek();
            q.poll();

            // new node f which is equal
            HuffmanNode f = new HuffmanNode();

            // to the sum of the frequency of the two nodes assigning values to the f node.
            f.data = x.data + y.data;
            f.c = '-';

            // first extracted node as left child.
            f.left = x;

            // second extracted node as the right child.
            f.right = y;

            // marking the f node as the root node.
            root = f;

            // add this node to the priority-queue.
            q.add(f);
        }

        // print the codes by traversing the tree
        assert root != null;
        printCode(root, "");
    }
}